[project]
name = "order-system"
version = "0.1.0"
description = "Sample order management domain logic"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"
